# v1 has certain type of predefined objects like Pod, Service, etc. 
apiVersion: v1
# The type of object we want to make.
# Pod is an object used to run a container - the smallest component we can create
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web # label to be used by a selector.
spec:
  containers:
    - name: client
      image: khutsokobela/multi-client
      ports:
        - containerPort: 3000
